<?php

function registrar_dummy_get_registrar_info() {

  return array(
    'registrar_dummy' => array(
      'name' => 'Dummy',
      'description' => 'Dummy domain registrar',
    )
  );
}

function registrar_dummy_admin_form() {
  $form = array();

  $form['registrar_dummy'] = array(
    '#type' => 'fieldset',
    '#title' => t('Dummy Registrar Settings'),
  );

  $form['registrar_dummy']['registrar_dummy_uri'] = array(
    '#type' => 'textfield',
    '#title' => t('Dummy Service URL'),
    '#default_value' => variable_get('registrar_dummy_uri', ''),
    '#description' => t("i.e. https://api.registrar_dummy.com/"),
    '#required' => TRUE,
  );

  return $form;
}

/**
 * Create a remote handle for a set of contact details.
 * @param object
 *   A contact node object
 * @return A handle
 */
function registrar_dummy_create_handle($contact) {
  return 'AAA';
}

/**
 * @see hook_check_domains()
 * @param $domain_list
 */
function registrar_dummy_check_domains($domain_list) {
  // Return some predefined answer.
  return array(
    'example.com' => array(
      'Domain' => 'example.com',
      'Available' => FALSE,
    ),
    'example-non-existant.com' => array(
      'Domain' => 'example.com',
      'Available' => TRUE,
    ),
    'drupal.org' => array(
      'Domain' => 'drupal.org',
      'Available' => FALSE,
  ));
}
